import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin,AiFillTwitterCircle} from 'react-icons/ai'
import Image  from 'next/image'
import Main from 'components/Main';
import About from 'components/About';
import Skills from 'components/Skills';
import Projects from 'components/Projects';
import Contact from 'components/Contact';
import ErrorBoundary from '../components/ErrorBoundary'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Quentin Fever Machine learning  </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorBoundary>
      <Main />
      <About />
      <Skills /> 
      <Projects />
      <Contact/>
      </ErrorBoundary>

    </div>
  )
}